package com.system.pojo;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.system.po.User;

public class UserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public String insertSelective(User record) {
        BEGIN();
        INSERT_INTO("user");
        
        if (record.getTelephone() != null) {
            VALUES("telephone", "#{telephone,jdbcType=INTEGER}");
        }
        
        if (record.getType() != null) {
            VALUES("`type`", "#{type,jdbcType=INTEGER}");
        }
        
        if (record.getPassword() != null) {
            VALUES("`password`", "#{password,jdbcType=VARCHAR}");
        }
        
        if (record.getPasswordSalt() != null) {
            VALUES("passwordSalt", "#{passwordSalt,jdbcType=VARCHAR}");
        }
        
        if (record.getNickName() != null) {
            VALUES("nickName", "#{nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            VALUES("email", "#{email,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            VALUES("createDate", "#{createDate,jdbcType=INTEGER}");
        }
        
        if (record.getCreateIp() != null) {
            VALUES("createIp", "#{createIp,jdbcType=INTEGER}");
        }
        
        if (record.getLastUpdateDate() != null) {
            VALUES("lastUpdateDate", "#{lastUpdateDate,jdbcType=INTEGER}");
        }
        
        if (record.getLastUpdateIp() != null) {
            VALUES("lastUpdateIp", "#{lastUpdateIp,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(User record) {
        BEGIN();
        UPDATE("user");
        
        if (record.getTelephone() != null) {
            SET("telephone = #{telephone,jdbcType=INTEGER}");
        }
        
        if (record.getType() != null) {
            SET("`type` = #{type,jdbcType=INTEGER}");
        }
        
        if (record.getPassword() != null) {
            SET("`password` = #{password,jdbcType=VARCHAR}");
        }
        
        if (record.getPasswordSalt() != null) {
            SET("passwordSalt = #{passwordSalt,jdbcType=VARCHAR}");
        }
        
        if (record.getNickName() != null) {
            SET("nickName = #{nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            SET("email = #{email,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            SET("createDate = #{createDate,jdbcType=INTEGER}");
        }
        
        if (record.getCreateIp() != null) {
            SET("createIp = #{createIp,jdbcType=INTEGER}");
        }
        
        if (record.getLastUpdateDate() != null) {
            SET("lastUpdateDate = #{lastUpdateDate,jdbcType=INTEGER}");
        }
        
        if (record.getLastUpdateIp() != null) {
            SET("lastUpdateIp = #{lastUpdateIp,jdbcType=INTEGER}");
        }
        
        WHERE("userId = #{userId,jdbcType=INTEGER}");
        
        return SQL();
    }
}