package com.system.pojo;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.system.po.Useradvance;

public class UseradvanceSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useradvance
     *
     * @mbggenerated
     */
    public String insertSelective(Useradvance record) {
        BEGIN();
        INSERT_INTO("useradvance");
        
        if (record.getUserid() != null) {
            VALUES("userId", "#{userid,jdbcType=INTEGER}");
        }
        
        if (record.getGender() != null) {
            VALUES("gender", "#{gender,jdbcType=INTEGER}");
        }
        
        if (record.getBirthday() != null) {
            VALUES("birthday", "#{birthday,jdbcType=INTEGER}");
        }
        
        if (record.getAddress() != null) {
            VALUES("address", "#{address,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedate() != null) {
            VALUES("createDate", "#{createdate,jdbcType=INTEGER}");
        }
        
        if (record.getCreateip() != null) {
            VALUES("createIp", "#{createip,jdbcType=INTEGER}");
        }
        
        if (record.getLastupdatedate() != null) {
            VALUES("lastUpdateDate", "#{lastupdatedate,jdbcType=INTEGER}");
        }
        
        if (record.getLastupdateip() != null) {
            VALUES("lastUpdateIp", "#{lastupdateip,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useradvance
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(Useradvance record) {
        BEGIN();
        UPDATE("useradvance");
        
        if (record.getGender() != null) {
            SET("gender = #{gender,jdbcType=INTEGER}");
        }
        
        if (record.getBirthday() != null) {
            SET("birthday = #{birthday,jdbcType=INTEGER}");
        }
        
        if (record.getAddress() != null) {
            SET("address = #{address,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedate() != null) {
            SET("createDate = #{createdate,jdbcType=INTEGER}");
        }
        
        if (record.getCreateip() != null) {
            SET("createIp = #{createip,jdbcType=INTEGER}");
        }
        
        if (record.getLastupdatedate() != null) {
            SET("lastUpdateDate = #{lastupdatedate,jdbcType=INTEGER}");
        }
        
        if (record.getLastupdateip() != null) {
            SET("lastUpdateIp = #{lastupdateip,jdbcType=INTEGER}");
        }
        
        WHERE("userId = #{userid,jdbcType=INTEGER}");
        
        return SQL();
    }
}