package com.system.pojo;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.system.po.UserAdvance;

public class UserAdvanceSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_advance
     *
     * @mbggenerated
     */
    public String insertSelective(UserAdvance record) {
        BEGIN();
        INSERT_INTO("user_advance");
        
        if (record.getUserId() != null) {
            VALUES("userId", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getGender() != null) {
            VALUES("gender", "#{gender,jdbcType=INTEGER}");
        }
        
        if (record.getBirthday() != null) {
            VALUES("birthday", "#{birthday,jdbcType=INTEGER}");
        }
        
        if (record.getAddress() != null) {
            VALUES("address", "#{address,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            VALUES("createDate", "#{createDate,jdbcType=INTEGER}");
        }
        
        if (record.getCreateIp() != null) {
            VALUES("createIp", "#{createIp,jdbcType=INTEGER}");
        }
        
        if (record.getLastUpdateDate() != null) {
            VALUES("lastUpdateDate", "#{lastUpdateDate,jdbcType=INTEGER}");
        }
        
        if (record.getLastUpdateIp() != null) {
            VALUES("lastUpdateIp", "#{lastUpdateIp,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_advance
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(UserAdvance record) {
        BEGIN();
        UPDATE("user_advance");
        
        if (record.getGender() != null) {
            SET("gender = #{gender,jdbcType=INTEGER}");
        }
        
        if (record.getBirthday() != null) {
            SET("birthday = #{birthday,jdbcType=INTEGER}");
        }
        
        if (record.getAddress() != null) {
            SET("address = #{address,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateDate() != null) {
            SET("createDate = #{createDate,jdbcType=INTEGER}");
        }
        
        if (record.getCreateIp() != null) {
            SET("createIp = #{createIp,jdbcType=INTEGER}");
        }
        
        if (record.getLastUpdateDate() != null) {
            SET("lastUpdateDate = #{lastUpdateDate,jdbcType=INTEGER}");
        }
        
        if (record.getLastUpdateIp() != null) {
            SET("lastUpdateIp = #{lastUpdateIp,jdbcType=INTEGER}");
        }
        
        WHERE("userId = #{userId,jdbcType=INTEGER}");
        
        return SQL();
    }
}