package com.system.pojo;

import com.system.po.User;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectKey;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user",
        "where userId = #{userId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user (telephone, `type`, ",
        "`password`, passwordSalt, ",
        "nickName, email, ",
        "createDate, createIp, ",
        "lastUpdateDate, lastUpdateIp)",
        "values (#{telephone,jdbcType=INTEGER}, #{type,jdbcType=INTEGER}, ",
        "#{password,jdbcType=VARCHAR}, #{passwordSalt,jdbcType=VARCHAR}, ",
        "#{nickName,jdbcType=VARCHAR}, #{email,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=INTEGER}, #{createIp,jdbcType=INTEGER}, ",
        "#{lastUpdateDate,jdbcType=INTEGER}, #{lastUpdateIp,jdbcType=INTEGER})"
    })
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="userId", before=false, resultType=Integer.class)
    int insert(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @InsertProvider(type=UserSqlProvider.class, method="insertSelective")
    @SelectKey(statement="SELECT LAST_INSERT_ID()", keyProperty="userId", before=false, resultType=Integer.class)
    int insertSelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "userId, telephone, `type`, `password`, passwordSalt, nickName, email, createDate, ",
        "createIp, lastUpdateDate, lastUpdateIp",
        "from user",
        "where userId = #{userId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="userId", property="userId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="telephone", property="telephone", jdbcType=JdbcType.INTEGER),
        @Result(column="type", property="type", jdbcType=JdbcType.INTEGER),
        @Result(column="password", property="password", jdbcType=JdbcType.VARCHAR),
        @Result(column="passwordSalt", property="passwordSalt", jdbcType=JdbcType.VARCHAR),
        @Result(column="nickName", property="nickName", jdbcType=JdbcType.VARCHAR),
        @Result(column="email", property="email", jdbcType=JdbcType.VARCHAR),
        @Result(column="createDate", property="createDate", jdbcType=JdbcType.INTEGER),
        @Result(column="createIp", property="createIp", jdbcType=JdbcType.INTEGER),
        @Result(column="lastUpdateDate", property="lastUpdateDate", jdbcType=JdbcType.INTEGER),
        @Result(column="lastUpdateIp", property="lastUpdateIp", jdbcType=JdbcType.INTEGER)
    })
    User selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @UpdateProvider(type=UserSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(User record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    @Update({
        "update user",
        "set telephone = #{telephone,jdbcType=INTEGER},",
          "`type` = #{type,jdbcType=INTEGER},",
          "`password` = #{password,jdbcType=VARCHAR},",
          "passwordSalt = #{passwordSalt,jdbcType=VARCHAR},",
          "nickName = #{nickName,jdbcType=VARCHAR},",
          "email = #{email,jdbcType=VARCHAR},",
          "createDate = #{createDate,jdbcType=INTEGER},",
          "createIp = #{createIp,jdbcType=INTEGER},",
          "lastUpdateDate = #{lastUpdateDate,jdbcType=INTEGER},",
          "lastUpdateIp = #{lastUpdateIp,jdbcType=INTEGER}",
        "where userId = #{userId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(User record);
}