package com.system.pojo;

import static org.apache.ibatis.jdbc.SqlBuilder.BEGIN;
import static org.apache.ibatis.jdbc.SqlBuilder.INSERT_INTO;
import static org.apache.ibatis.jdbc.SqlBuilder.SET;
import static org.apache.ibatis.jdbc.SqlBuilder.SQL;
import static org.apache.ibatis.jdbc.SqlBuilder.UPDATE;
import static org.apache.ibatis.jdbc.SqlBuilder.VALUES;
import static org.apache.ibatis.jdbc.SqlBuilder.WHERE;

import com.system.po.User;

public class UserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public String insertSelective(User record) {
        BEGIN();
        INSERT_INTO("user");
        
        if (record.getUserid() != null) {
            VALUES("userId", "#{userid,jdbcType=INTEGER}");
        }
        
        if (record.getTelephone() != null) {
            VALUES("telephone", "#{telephone,jdbcType=INTEGER}");
        }
        
        if (record.getType() != null) {
            VALUES("`type`", "#{type,jdbcType=INTEGER}");
        }
        
        if (record.getPassword() != null) {
            VALUES("`password`", "#{password,jdbcType=VARCHAR}");
        }
        
        if (record.getPasswordsalt() != null) {
            VALUES("passwordSalt", "#{passwordsalt,jdbcType=VARCHAR}");
        }
        
        if (record.getNickname() != null) {
            VALUES("nickName", "#{nickname,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            VALUES("email", "#{email,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedate() != null) {
            VALUES("createDate", "#{createdate,jdbcType=INTEGER}");
        }
        
        if (record.getCreateip() != null) {
            VALUES("createIp", "#{createip,jdbcType=INTEGER}");
        }
        
        if (record.getLastupdatedate() != null) {
            VALUES("lastUpdateDate", "#{lastupdatedate,jdbcType=INTEGER}");
        }
        
        if (record.getLastupdateip() != null) {
            VALUES("lastUpdateIp", "#{lastupdateip,jdbcType=INTEGER}");
        }
        
        return SQL();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user
     *
     * @mbggenerated
     */
    public String updateByPrimaryKeySelective(User record) {
        BEGIN();
        UPDATE("user");
        
        if (record.getTelephone() != null) {
            SET("telephone = #{telephone,jdbcType=INTEGER}");
        }
        
        if (record.getType() != null) {
            SET("`type` = #{type,jdbcType=INTEGER}");
        }
        
        if (record.getPassword() != null) {
            SET("`password` = #{password,jdbcType=VARCHAR}");
        }
        
        if (record.getPasswordsalt() != null) {
            SET("passwordSalt = #{passwordsalt,jdbcType=VARCHAR}");
        }
        
        if (record.getNickname() != null) {
            SET("nickName = #{nickname,jdbcType=VARCHAR}");
        }
        
        if (record.getEmail() != null) {
            SET("email = #{email,jdbcType=VARCHAR}");
        }
        
        if (record.getCreatedate() != null) {
            SET("createDate = #{createdate,jdbcType=INTEGER}");
        }
        
        if (record.getCreateip() != null) {
            SET("createIp = #{createip,jdbcType=INTEGER}");
        }
        
        if (record.getLastupdatedate() != null) {
            SET("lastUpdateDate = #{lastupdatedate,jdbcType=INTEGER}");
        }
        
        if (record.getLastupdateip() != null) {
            SET("lastUpdateIp = #{lastupdateip,jdbcType=INTEGER}");
        }
        
        WHERE("userId = #{userid,jdbcType=INTEGER}");
        
        return SQL();
    }
}