package com.system.pojo;

import com.system.po.UserAdvance;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UserAdvanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_advance
     *
     * @mbggenerated
     */
    @Delete({
        "delete from user_advance",
        "where userId = #{userId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_advance
     *
     * @mbggenerated
     */
    @Insert({
        "insert into user_advance (userId, gender, ",
        "birthday, address, ",
        "createDate, createIp, ",
        "lastUpdateDate, lastUpdateIp)",
        "values (#{userId,jdbcType=INTEGER}, #{gender,jdbcType=INTEGER}, ",
        "#{birthday,jdbcType=INTEGER}, #{address,jdbcType=VARCHAR}, ",
        "#{createDate,jdbcType=INTEGER}, #{createIp,jdbcType=INTEGER}, ",
        "#{lastUpdateDate,jdbcType=INTEGER}, #{lastUpdateIp,jdbcType=INTEGER})"
    })
    int insert(UserAdvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_advance
     *
     * @mbggenerated
     */
    @InsertProvider(type=UserAdvanceSqlProvider.class, method="insertSelective")
    int insertSelective(UserAdvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_advance
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "userId, gender, birthday, address, createDate, createIp, lastUpdateDate, lastUpdateIp",
        "from user_advance",
        "where userId = #{userId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="userId", property="userId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="gender", property="gender", jdbcType=JdbcType.INTEGER),
        @Result(column="birthday", property="birthday", jdbcType=JdbcType.INTEGER),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="createDate", property="createDate", jdbcType=JdbcType.INTEGER),
        @Result(column="createIp", property="createIp", jdbcType=JdbcType.INTEGER),
        @Result(column="lastUpdateDate", property="lastUpdateDate", jdbcType=JdbcType.INTEGER),
        @Result(column="lastUpdateIp", property="lastUpdateIp", jdbcType=JdbcType.INTEGER)
    })
    UserAdvance selectByPrimaryKey(Integer userId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_advance
     *
     * @mbggenerated
     */
    @UpdateProvider(type=UserAdvanceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(UserAdvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_advance
     *
     * @mbggenerated
     */
    @Update({
        "update user_advance",
        "set gender = #{gender,jdbcType=INTEGER},",
          "birthday = #{birthday,jdbcType=INTEGER},",
          "address = #{address,jdbcType=VARCHAR},",
          "createDate = #{createDate,jdbcType=INTEGER},",
          "createIp = #{createIp,jdbcType=INTEGER},",
          "lastUpdateDate = #{lastUpdateDate,jdbcType=INTEGER},",
          "lastUpdateIp = #{lastUpdateIp,jdbcType=INTEGER}",
        "where userId = #{userId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(UserAdvance record);
}