package com.system.pojo;

import com.system.po.Useradvance;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface UseradvanceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useradvance
     *
     * @mbggenerated
     */
    @Delete({
        "delete from useradvance",
        "where userId = #{userid,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useradvance
     *
     * @mbggenerated
     */
    @Insert({
        "insert into useradvance (userId, gender, ",
        "birthday, address, ",
        "createDate, createIp, ",
        "lastUpdateDate, lastUpdateIp)",
        "values (#{userid,jdbcType=INTEGER}, #{gender,jdbcType=INTEGER}, ",
        "#{birthday,jdbcType=INTEGER}, #{address,jdbcType=VARCHAR}, ",
        "#{createdate,jdbcType=INTEGER}, #{createip,jdbcType=INTEGER}, ",
        "#{lastupdatedate,jdbcType=INTEGER}, #{lastupdateip,jdbcType=INTEGER})"
    })
    int insert(Useradvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useradvance
     *
     * @mbggenerated
     */
    @InsertProvider(type=UseradvanceSqlProvider.class, method="insertSelective")
    int insertSelective(Useradvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useradvance
     *
     * @mbggenerated
     */
    @Select({
        "select",
        "userId, gender, birthday, address, createDate, createIp, lastUpdateDate, lastUpdateIp",
        "from useradvance",
        "where userId = #{userid,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="userId", property="userid", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="gender", property="gender", jdbcType=JdbcType.INTEGER),
        @Result(column="birthday", property="birthday", jdbcType=JdbcType.INTEGER),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="createDate", property="createdate", jdbcType=JdbcType.INTEGER),
        @Result(column="createIp", property="createip", jdbcType=JdbcType.INTEGER),
        @Result(column="lastUpdateDate", property="lastupdatedate", jdbcType=JdbcType.INTEGER),
        @Result(column="lastUpdateIp", property="lastupdateip", jdbcType=JdbcType.INTEGER)
    })
    Useradvance selectByPrimaryKey(Integer userid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useradvance
     *
     * @mbggenerated
     */
    @UpdateProvider(type=UseradvanceSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Useradvance record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table useradvance
     *
     * @mbggenerated
     */
    @Update({
        "update useradvance",
        "set gender = #{gender,jdbcType=INTEGER},",
          "birthday = #{birthday,jdbcType=INTEGER},",
          "address = #{address,jdbcType=VARCHAR},",
          "createDate = #{createdate,jdbcType=INTEGER},",
          "createIp = #{createip,jdbcType=INTEGER},",
          "lastUpdateDate = #{lastupdatedate,jdbcType=INTEGER},",
          "lastUpdateIp = #{lastupdateip,jdbcType=INTEGER}",
        "where userId = #{userid,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Useradvance record);
}