package com.system.po;

public class UserAdvance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advance.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advance.gender
     *
     * @mbggenerated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advance.birthday
     *
     * @mbggenerated
     */
    private Integer birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advance.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advance.createDate
     *
     * @mbggenerated
     */
    private Integer createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advance.createIp
     *
     * @mbggenerated
     */
    private Integer createIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advance.lastUpdateDate
     *
     * @mbggenerated
     */
    private Integer lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_advance.lastUpdateIp
     *
     * @mbggenerated
     */
    private Integer lastUpdateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advance.userId
     *
     * @return the value of user_advance.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advance.userId
     *
     * @param userId the value for user_advance.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advance.gender
     *
     * @return the value of user_advance.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advance.gender
     *
     * @param gender the value for user_advance.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advance.birthday
     *
     * @return the value of user_advance.birthday
     *
     * @mbggenerated
     */
    public Integer getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advance.birthday
     *
     * @param birthday the value for user_advance.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Integer birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advance.address
     *
     * @return the value of user_advance.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advance.address
     *
     * @param address the value for user_advance.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advance.createDate
     *
     * @return the value of user_advance.createDate
     *
     * @mbggenerated
     */
    public Integer getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advance.createDate
     *
     * @param createDate the value for user_advance.createDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Integer createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advance.createIp
     *
     * @return the value of user_advance.createIp
     *
     * @mbggenerated
     */
    public Integer getCreateIp() {
        return createIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advance.createIp
     *
     * @param createIp the value for user_advance.createIp
     *
     * @mbggenerated
     */
    public void setCreateIp(Integer createIp) {
        this.createIp = createIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advance.lastUpdateDate
     *
     * @return the value of user_advance.lastUpdateDate
     *
     * @mbggenerated
     */
    public Integer getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advance.lastUpdateDate
     *
     * @param lastUpdateDate the value for user_advance.lastUpdateDate
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Integer lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_advance.lastUpdateIp
     *
     * @return the value of user_advance.lastUpdateIp
     *
     * @mbggenerated
     */
    public Integer getLastUpdateIp() {
        return lastUpdateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_advance.lastUpdateIp
     *
     * @param lastUpdateIp the value for user_advance.lastUpdateIp
     *
     * @mbggenerated
     */
    public void setLastUpdateIp(Integer lastUpdateIp) {
        this.lastUpdateIp = lastUpdateIp;
    }
}