package com.system.po;

public class Useradvance {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useradvance.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useradvance.gender
     *
     * @mbggenerated
     */
    private Integer gender;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useradvance.birthday
     *
     * @mbggenerated
     */
    private Integer birthday;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useradvance.address
     *
     * @mbggenerated
     */
    private String address;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useradvance.createDate
     *
     * @mbggenerated
     */
    private Integer createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useradvance.createIp
     *
     * @mbggenerated
     */
    private Integer createip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useradvance.lastUpdateDate
     *
     * @mbggenerated
     */
    private Integer lastupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column useradvance.lastUpdateIp
     *
     * @mbggenerated
     */
    private Integer lastupdateip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useradvance.userId
     *
     * @return the value of useradvance.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useradvance.userId
     *
     * @param userid the value for useradvance.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useradvance.gender
     *
     * @return the value of useradvance.gender
     *
     * @mbggenerated
     */
    public Integer getGender() {
        return gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useradvance.gender
     *
     * @param gender the value for useradvance.gender
     *
     * @mbggenerated
     */
    public void setGender(Integer gender) {
        this.gender = gender;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useradvance.birthday
     *
     * @return the value of useradvance.birthday
     *
     * @mbggenerated
     */
    public Integer getBirthday() {
        return birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useradvance.birthday
     *
     * @param birthday the value for useradvance.birthday
     *
     * @mbggenerated
     */
    public void setBirthday(Integer birthday) {
        this.birthday = birthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useradvance.address
     *
     * @return the value of useradvance.address
     *
     * @mbggenerated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useradvance.address
     *
     * @param address the value for useradvance.address
     *
     * @mbggenerated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useradvance.createDate
     *
     * @return the value of useradvance.createDate
     *
     * @mbggenerated
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useradvance.createDate
     *
     * @param createdate the value for useradvance.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useradvance.createIp
     *
     * @return the value of useradvance.createIp
     *
     * @mbggenerated
     */
    public Integer getCreateip() {
        return createip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useradvance.createIp
     *
     * @param createip the value for useradvance.createIp
     *
     * @mbggenerated
     */
    public void setCreateip(Integer createip) {
        this.createip = createip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useradvance.lastUpdateDate
     *
     * @return the value of useradvance.lastUpdateDate
     *
     * @mbggenerated
     */
    public Integer getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useradvance.lastUpdateDate
     *
     * @param lastupdatedate the value for useradvance.lastUpdateDate
     *
     * @mbggenerated
     */
    public void setLastupdatedate(Integer lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column useradvance.lastUpdateIp
     *
     * @return the value of useradvance.lastUpdateIp
     *
     * @mbggenerated
     */
    public Integer getLastupdateip() {
        return lastupdateip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column useradvance.lastUpdateIp
     *
     * @param lastupdateip the value for useradvance.lastUpdateIp
     *
     * @mbggenerated
     */
    public void setLastupdateip(Integer lastupdateip) {
        this.lastupdateip = lastupdateip;
    }
}