package com.system.po;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userId
     *
     * @mbggenerated
     */
    private Integer userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.telephone
     *
     * @mbggenerated
     */
    private Integer telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.passwordSalt
     *
     * @mbggenerated
     */
    private String passwordSalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickName
     *
     * @mbggenerated
     */
    private String nickName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createDate
     *
     * @mbggenerated
     */
    private Integer createDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createIp
     *
     * @mbggenerated
     */
    private Integer createIp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastUpdateDate
     *
     * @mbggenerated
     */
    private Integer lastUpdateDate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastUpdateIp
     *
     * @mbggenerated
     */
    private Integer lastUpdateIp;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userId
     *
     * @return the value of user.userId
     *
     * @mbggenerated
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userId
     *
     * @param userId the value for user.userId
     *
     * @mbggenerated
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telephone
     *
     * @return the value of user.telephone
     *
     * @mbggenerated
     */
    public Integer getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telephone
     *
     * @param telephone the value for user.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.type
     *
     * @return the value of user.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.type
     *
     * @param type the value for user.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.passwordSalt
     *
     * @return the value of user.passwordSalt
     *
     * @mbggenerated
     */
    public String getPasswordSalt() {
        return passwordSalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.passwordSalt
     *
     * @param passwordSalt the value for user.passwordSalt
     *
     * @mbggenerated
     */
    public void setPasswordSalt(String passwordSalt) {
        this.passwordSalt = passwordSalt == null ? null : passwordSalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickName
     *
     * @return the value of user.nickName
     *
     * @mbggenerated
     */
    public String getNickName() {
        return nickName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickName
     *
     * @param nickName the value for user.nickName
     *
     * @mbggenerated
     */
    public void setNickName(String nickName) {
        this.nickName = nickName == null ? null : nickName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createDate
     *
     * @return the value of user.createDate
     *
     * @mbggenerated
     */
    public Integer getCreateDate() {
        return createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createDate
     *
     * @param createDate the value for user.createDate
     *
     * @mbggenerated
     */
    public void setCreateDate(Integer createDate) {
        this.createDate = createDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createIp
     *
     * @return the value of user.createIp
     *
     * @mbggenerated
     */
    public Integer getCreateIp() {
        return createIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createIp
     *
     * @param createIp the value for user.createIp
     *
     * @mbggenerated
     */
    public void setCreateIp(Integer createIp) {
        this.createIp = createIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastUpdateDate
     *
     * @return the value of user.lastUpdateDate
     *
     * @mbggenerated
     */
    public Integer getLastUpdateDate() {
        return lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastUpdateDate
     *
     * @param lastUpdateDate the value for user.lastUpdateDate
     *
     * @mbggenerated
     */
    public void setLastUpdateDate(Integer lastUpdateDate) {
        this.lastUpdateDate = lastUpdateDate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastUpdateIp
     *
     * @return the value of user.lastUpdateIp
     *
     * @mbggenerated
     */
    public Integer getLastUpdateIp() {
        return lastUpdateIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastUpdateIp
     *
     * @param lastUpdateIp the value for user.lastUpdateIp
     *
     * @mbggenerated
     */
    public void setLastUpdateIp(Integer lastUpdateIp) {
        this.lastUpdateIp = lastUpdateIp;
    }
}