package com.system.po;

public class User {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.userId
     *
     * @mbggenerated
     */
    private Integer userid;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.telephone
     *
     * @mbggenerated
     */
    private Integer telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.type
     *
     * @mbggenerated
     */
    private Integer type;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.password
     *
     * @mbggenerated
     */
    private String password;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.passwordSalt
     *
     * @mbggenerated
     */
    private String passwordsalt;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.nickName
     *
     * @mbggenerated
     */
    private String nickname;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.email
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createDate
     *
     * @mbggenerated
     */
    private Integer createdate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.createIp
     *
     * @mbggenerated
     */
    private Integer createip;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastUpdateDate
     *
     * @mbggenerated
     */
    private Integer lastupdatedate;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user.lastUpdateIp
     *
     * @mbggenerated
     */
    private Integer lastupdateip;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.userId
     *
     * @return the value of user.userId
     *
     * @mbggenerated
     */
    public Integer getUserid() {
        return userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.userId
     *
     * @param userid the value for user.userId
     *
     * @mbggenerated
     */
    public void setUserid(Integer userid) {
        this.userid = userid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.telephone
     *
     * @return the value of user.telephone
     *
     * @mbggenerated
     */
    public Integer getTelephone() {
        return telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.telephone
     *
     * @param telephone the value for user.telephone
     *
     * @mbggenerated
     */
    public void setTelephone(Integer telephone) {
        this.telephone = telephone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.type
     *
     * @return the value of user.type
     *
     * @mbggenerated
     */
    public Integer getType() {
        return type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.type
     *
     * @param type the value for user.type
     *
     * @mbggenerated
     */
    public void setType(Integer type) {
        this.type = type;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.password
     *
     * @return the value of user.password
     *
     * @mbggenerated
     */
    public String getPassword() {
        return password;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.password
     *
     * @param password the value for user.password
     *
     * @mbggenerated
     */
    public void setPassword(String password) {
        this.password = password == null ? null : password.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.passwordSalt
     *
     * @return the value of user.passwordSalt
     *
     * @mbggenerated
     */
    public String getPasswordsalt() {
        return passwordsalt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.passwordSalt
     *
     * @param passwordsalt the value for user.passwordSalt
     *
     * @mbggenerated
     */
    public void setPasswordsalt(String passwordsalt) {
        this.passwordsalt = passwordsalt == null ? null : passwordsalt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.nickName
     *
     * @return the value of user.nickName
     *
     * @mbggenerated
     */
    public String getNickname() {
        return nickname;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.nickName
     *
     * @param nickname the value for user.nickName
     *
     * @mbggenerated
     */
    public void setNickname(String nickname) {
        this.nickname = nickname == null ? null : nickname.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.email
     *
     * @return the value of user.email
     *
     * @mbggenerated
     */
    public String getEmail() {
        return email;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.email
     *
     * @param email the value for user.email
     *
     * @mbggenerated
     */
    public void setEmail(String email) {
        this.email = email == null ? null : email.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createDate
     *
     * @return the value of user.createDate
     *
     * @mbggenerated
     */
    public Integer getCreatedate() {
        return createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createDate
     *
     * @param createdate the value for user.createDate
     *
     * @mbggenerated
     */
    public void setCreatedate(Integer createdate) {
        this.createdate = createdate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.createIp
     *
     * @return the value of user.createIp
     *
     * @mbggenerated
     */
    public Integer getCreateip() {
        return createip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.createIp
     *
     * @param createip the value for user.createIp
     *
     * @mbggenerated
     */
    public void setCreateip(Integer createip) {
        this.createip = createip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastUpdateDate
     *
     * @return the value of user.lastUpdateDate
     *
     * @mbggenerated
     */
    public Integer getLastupdatedate() {
        return lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastUpdateDate
     *
     * @param lastupdatedate the value for user.lastUpdateDate
     *
     * @mbggenerated
     */
    public void setLastupdatedate(Integer lastupdatedate) {
        this.lastupdatedate = lastupdatedate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user.lastUpdateIp
     *
     * @return the value of user.lastUpdateIp
     *
     * @mbggenerated
     */
    public Integer getLastupdateip() {
        return lastupdateip;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user.lastUpdateIp
     *
     * @param lastupdateip the value for user.lastUpdateIp
     *
     * @mbggenerated
     */
    public void setLastupdateip(Integer lastupdateip) {
        this.lastupdateip = lastupdateip;
    }
}